RFT_GLOB = {}
RFT_GLOB.DEF_ROLL = 100

RFT_GLOB.DEF_NORMAL_DAMAGE = 1
RFT_GLOB.DEF_CRIT_DAMAGE = 2 -- Default total damage when player critically hits.
RFT_GLOB.DEF_CRIT_CHANCE = 50 -- Default (attack - defend) roll difference to make an attack critical. SO ACTUALLY CHANCES -DROP- WHEN WE -INCREASE- THE NUMBER.

RFT_GLOB.MAX_HEALTH = 10 -- to be implemented
RFT_GLOB.NOTIFY_RANGE = 40 -- in yards. default is 40.

RFT_GLOB.ADVANTAGES = 
{
	CLASS =
	{
		WARRIOR =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		PALADIN =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		PRIEST =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		HUNTER =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		ROGUE =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		SHAMAN =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		WARLOCK =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		DEATH_KNIGHT =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		MAGE =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		MONK =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		DRUID =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		DEMON_HUNTER =
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
	},
	RACE =
	{
		HUMAN = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		NIGHTELF = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		DWARF = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		GNOME = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		DRAENEI = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		WORGEN = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		ORC = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		TROLL = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		UNDEAD = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		TAUREN = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		BLOODELF = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		GOBLIN = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		PANDAREN = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		VOIDELF = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		NIGHTBORNE = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		HIGHMOUNTAIN_TAUREN = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
		LIGHTFORGED_DRAENEI = 
		{
			ATTACK = 0,
			DEFEND = 0,
			CRIT_CHANCE = RFT_GLOB.DEF_CRIT_CHANCE,
			CRIT_DAMAGE = RFT_GLOB.DEF_CRIT_DAMAGE
		},
	}
}

RFT_GLOB_LIST =
{
	'ADVANTAGES.CLASS.WARRIOR.CRIT_CHANCE',
	'ADVANTAGES.CLASS.WARRIOR.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.WARRIOR.ATTACK',
	'ADVANTAGES.CLASS.WARRIOR.DEFEND',
	'ADVANTAGES.CLASS.SHAMAN.CRIT_CHANCE',
	'ADVANTAGES.CLASS.SHAMAN.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.SHAMAN.ATTACK',
	'ADVANTAGES.CLASS.SHAMAN.DEFEND',
	'ADVANTAGES.CLASS.DEMON_HUNTER.CRIT_CHANCE',
	'ADVANTAGES.CLASS.DEMON_HUNTER.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.DEMON_HUNTER.ATTACK',
	'ADVANTAGES.CLASS.DEMON_HUNTER.DEFEND',
	'ADVANTAGES.CLASS.ROGUE.CRIT_CHANCE',
	'ADVANTAGES.CLASS.ROGUE.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.ROGUE.ATTACK',
	'ADVANTAGES.CLASS.ROGUE.DEFEND',
	'ADVANTAGES.CLASS.WARLOCK.CRIT_CHANCE',
	'ADVANTAGES.CLASS.WARLOCK.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.WARLOCK.ATTACK',
	'ADVANTAGES.CLASS.WARLOCK.DEFEND',
	'ADVANTAGES.CLASS.DEATH_KNIGHT.CRIT_CHANCE',
	'ADVANTAGES.CLASS.DEATH_KNIGHT.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.DEATH_KNIGHT.ATTACK',
	'ADVANTAGES.CLASS.DEATH_KNIGHT.DEFEND',
	'ADVANTAGES.CLASS.PRIEST.CRIT_CHANCE',
	'ADVANTAGES.CLASS.PRIEST.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.PRIEST.ATTACK',
	'ADVANTAGES.CLASS.PRIEST.DEFEND',
	'ADVANTAGES.CLASS.MONK.CRIT_CHANCE',
	'ADVANTAGES.CLASS.MONK.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.MONK.ATTACK',
	'ADVANTAGES.CLASS.MONK.DEFEND',
	'ADVANTAGES.CLASS.HUNTER.CRIT_CHANCE',
	'ADVANTAGES.CLASS.HUNTER.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.HUNTER.ATTACK',
	'ADVANTAGES.CLASS.HUNTER.DEFEND',
	'ADVANTAGES.CLASS.PALADIN.CRIT_CHANCE',
	'ADVANTAGES.CLASS.PALADIN.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.PALADIN.ATTACK',
	'ADVANTAGES.CLASS.PALADIN.DEFEND',
	'ADVANTAGES.CLASS.DRUID.CRIT_CHANCE',
	'ADVANTAGES.CLASS.DRUID.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.DRUID.ATTACK',
	'ADVANTAGES.CLASS.DRUID.DEFEND',
	'ADVANTAGES.CLASS.MAGE.CRIT_CHANCE',
	'ADVANTAGES.CLASS.MAGE.CRIT_DAMAGE',
	'ADVANTAGES.CLASS.MAGE.ATTACK',
	'ADVANTAGES.CLASS.MAGE.DEFEND',
	'ADVANTAGES.RACE.WORGEN.CRIT_CHANCE',
	'ADVANTAGES.RACE.WORGEN.CRIT_DAMAGE',
	'ADVANTAGES.RACE.WORGEN.ATTACK',
	'ADVANTAGES.RACE.WORGEN.DEFEND',
	'ADVANTAGES.RACE.VOIDELF.CRIT_CHANCE',
	'ADVANTAGES.RACE.VOIDELF.CRIT_DAMAGE',
	'ADVANTAGES.RACE.VOIDELF.ATTACK',
	'ADVANTAGES.RACE.VOIDELF.DEFEND',
	'ADVANTAGES.RACE.DRAENEI.CRIT_CHANCE',
	'ADVANTAGES.RACE.DRAENEI.CRIT_DAMAGE',
	'ADVANTAGES.RACE.DRAENEI.ATTACK',
	'ADVANTAGES.RACE.DRAENEI.DEFEND',
	'ADVANTAGES.RACE.LIGHTFORGED_DRAENEI.CRIT_CHANCE',
	'ADVANTAGES.RACE.LIGHTFORGED_DRAENEI.CRIT_DAMAGE',
	'ADVANTAGES.RACE.LIGHTFORGED_DRAENEI.ATTACK',
	'ADVANTAGES.RACE.LIGHTFORGED_DRAENEI.DEFEND',
	'ADVANTAGES.RACE.HUMAN.CRIT_CHANCE',
	'ADVANTAGES.RACE.HUMAN.CRIT_DAMAGE',
	'ADVANTAGES.RACE.HUMAN.ATTACK',
	'ADVANTAGES.RACE.HUMAN.DEFEND',
	'ADVANTAGES.RACE.UNDEAD.CRIT_CHANCE',
	'ADVANTAGES.RACE.UNDEAD.CRIT_DAMAGE',
	'ADVANTAGES.RACE.UNDEAD.ATTACK',
	'ADVANTAGES.RACE.UNDEAD.DEFEND',
	'ADVANTAGES.RACE.DWARF.CRIT_CHANCE',
	'ADVANTAGES.RACE.DWARF.CRIT_DAMAGE',
	'ADVANTAGES.RACE.DWARF.ATTACK',
	'ADVANTAGES.RACE.DWARF.DEFEND',
	'ADVANTAGES.RACE.NIGHTELF.CRIT_CHANCE',
	'ADVANTAGES.RACE.NIGHTELF.CRIT_DAMAGE',
	'ADVANTAGES.RACE.NIGHTELF.ATTACK',
	'ADVANTAGES.RACE.NIGHTELF.DEFEND',
	'ADVANTAGES.RACE.HIGHMOUNTAIN_TAUREN.CRIT_CHANCE',
	'ADVANTAGES.RACE.HIGHMOUNTAIN_TAUREN.CRIT_DAMAGE',
	'ADVANTAGES.RACE.HIGHMOUNTAIN_TAUREN.ATTACK',
	'ADVANTAGES.RACE.HIGHMOUNTAIN_TAUREN.DEFEND',
	'ADVANTAGES.RACE.TROLL.CRIT_CHANCE',
	'ADVANTAGES.RACE.TROLL.CRIT_DAMAGE',
	'ADVANTAGES.RACE.TROLL.ATTACK',
	'ADVANTAGES.RACE.TROLL.DEFEND',
	'ADVANTAGES.RACE.PANDAREN.CRIT_CHANCE',
	'ADVANTAGES.RACE.PANDAREN.CRIT_DAMAGE',
	'ADVANTAGES.RACE.PANDAREN.ATTACK',
	'ADVANTAGES.RACE.PANDAREN.DEFEND',
	'ADVANTAGES.RACE.GNOME.CRIT_CHANCE',
	'ADVANTAGES.RACE.GNOME.CRIT_DAMAGE',
	'ADVANTAGES.RACE.GNOME.ATTACK',
	'ADVANTAGES.RACE.GNOME.DEFEND',
	'ADVANTAGES.RACE.NIGHTBORNE.CRIT_CHANCE',
	'ADVANTAGES.RACE.NIGHTBORNE.CRIT_DAMAGE',
	'ADVANTAGES.RACE.NIGHTBORNE.ATTACK',
	'ADVANTAGES.RACE.NIGHTBORNE.DEFEND',
	'ADVANTAGES.RACE.BLOODELF.CRIT_CHANCE',
	'ADVANTAGES.RACE.BLOODELF.CRIT_DAMAGE',
	'ADVANTAGES.RACE.BLOODELF.ATTACK',
	'ADVANTAGES.RACE.BLOODELF.DEFEND',
	'ADVANTAGES.RACE.GOBLIN.CRIT_CHANCE',
	'ADVANTAGES.RACE.GOBLIN.CRIT_DAMAGE',
	'ADVANTAGES.RACE.GOBLIN.ATTACK',
	'ADVANTAGES.RACE.GOBLIN.DEFEND',
	'ADVANTAGES.RACE.TAUREN.CRIT_CHANCE',
	'ADVANTAGES.RACE.TAUREN.CRIT_DAMAGE',
	'ADVANTAGES.RACE.TAUREN.ATTACK',
	'ADVANTAGES.RACE.TAUREN.DEFEND',
	'ADVANTAGES.RACE.ORC.CRIT_CHANCE',
	'ADVANTAGES.RACE.ORC.CRIT_DAMAGE',
	'ADVANTAGES.RACE.ORC.ATTACK',
	'ADVANTAGES.RACE.ORC.DEFEND',
	'NOTIFY_RANGE',
	'DEF_CRIT_DAMAGE',
	'MAX_HEALTH',
	'DEF_ROLL',
	'DEF_CRIT_CHANCE',
	'DEF_NORMAL_DAMAGE'
}

RFT_GLOB_DEF = RFT_GLOB	